
name: TestNG-Git-Github Tests

on:
  push:
    branches: [ "master" ]

  schedule:
      - cron: '0 5 * * 3' #UTC


permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install nodejs and npm
      uses: actions/setup-node@v3
      with:
           node-version: 18

    - name: Install junit merge package
      run: npm install -g junit-merge

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    - name: Run tests
      run: mvn clean test -Dfile="testng.xml"

    - name: Merge junit xml reports
      if: always()
      run: junit-merge -o target/results.xml -d target/surefire-reports/junitreports/

    - name: Test Report
      id: test_report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: TestNG Tests            # Name of the check run which will be created
        path: target/results.xml    # Path to test results
        reporter: java-junit       # Format of test results
        max-annotations: '30'

    - name: Read test report results
      if: always()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: | 
        echo "Test Results Outputs: "
        echo "steps.test_report.outputs"
      

