
name: TestNG-Git-Github Tests

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    - name: Run tests
      run: mvn clean test -Dfile="testng.xml"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: TestNG Tests            # Name of the check run which will be created
        path: target/surefire-reports/junitreports/*.xml    # Path to test results
        reporter: java-junit       # Format of test results
        max-annotations: '30'

