
name: TestNG-Git-Github Tests

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    - name: Run tests
      run: mvn clean test -Dfile="testng.xml"

